"IMAGE","FILE","TASK",ERROR"
"celery:latest","/usr/local/lib/libpython3.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-10.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-10.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-10.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-10.0.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-14.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-14.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-14.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-14.0.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-6.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-6.0.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-7.1.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-7.1.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-8.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-8.0.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-9.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-9.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-9.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/distutils/command/wininst-9.0.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_bisect.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_cn.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_hk.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_iso2022.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_jp.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_kr.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_codecs_tw.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_crypt.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_csv.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_ctypes_test.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_curses.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_curses_panel.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_datetime.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_dbm.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_decimal.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_elementtree.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_gdbm.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_lsprof.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_md5.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_multibytecodec.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_multiprocessing.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_pickle.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_posixsubprocess.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_random.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_sha1.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_sha256.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_sha512.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_socket.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_sqlite3.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_struct.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_testbuffer.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_testcapi.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_testimportmultiple.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_testmultiphase.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/_tkinter.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/array.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/audioop.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/binascii.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/cmath.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/fcntl.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/grp.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/math.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/mmap.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/nis.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/ossaudiodev.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/parser.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/pyexpat.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/resource.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/select.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/spwd.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/syslog.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/termios.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/unicodedata.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/xxlimited.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/lib-dynload/zlib.cpython-35m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/t32.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/t64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/w32.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/w64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"celery:latest","/usr/local/lib/python3.5/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"celery:latest","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
