"FILE","ERROR"
"/usr/local/lib/libpython3.so","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-10.0-amd64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-10.0-amd64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-10.0.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-10.0.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-6.0.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-6.0.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-7.1.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-7.1.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-8.0.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-8.0.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-9.0-amd64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-9.0-amd64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/distutils/command/wininst-9.0.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/distutils/command/wininst-9.0.exe","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_bisect.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_bz2.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_cn.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_hk.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_iso2022.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_jp.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_kr.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_codecs_tw.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_crypt.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_csv.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_ctypes.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_ctypes_test.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_curses.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_curses_panel.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_datetime.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_dbm.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_decimal.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_elementtree.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_gdbm.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_hashlib.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_heapq.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_json.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_lsprof.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_lzma.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_md5.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_multibytecodec.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_multiprocessing.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_opcode.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_pickle.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_posixsubprocess.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_random.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_sha1.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_sha256.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_sha512.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_socket.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_sqlite3.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_ssl.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_struct.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_testbuffer.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_testcapi.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_testimportmultiple.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/_tkinter.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/array.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/audioop.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/binascii.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/cmath.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/fcntl.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/grp.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/math.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/mmap.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/nis.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/ossaudiodev.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/parser.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/pyexpat.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/readline.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/resource.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/select.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/spwd.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/syslog.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/termios.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/time.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/unicodedata.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/xxlimited.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/lib-dynload/zlib.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/_mysql.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/t32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/t32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/t64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/t64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/w32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/w32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/w64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/pip/_vendor/distlib/w64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/psycopg2/_psycopg.cpython-34m.so","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-arm-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli-arm-32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/cli.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-64.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-64.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-arm-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui-arm-32.exe","no package identified in executable file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui.exe","unable to find PE name in file"
"/usr/local/lib/python3.4/site-packages/setuptools/gui.exe","no package identified in executable file"
"/var/lib/dpkg/info/bash.preinst","no package identified in executable file"
