"IMAGE","FILE","TASK",ERROR"
"hylang:latest","/usr/local/lib/libpython3.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_asyncio.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_bisect.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_blake2.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_bz2.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_cn.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_hk.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_iso2022.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_jp.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_kr.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_codecs_tw.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_contextvars.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_crypt.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_csv.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_ctypes_test.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_curses.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_curses_panel.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_datetime.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_dbm.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_decimal.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_elementtree.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_gdbm.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_hashlib.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_heapq.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_json.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_lsprof.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_lzma.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_md5.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_multibytecodec.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_multiprocessing.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_opcode.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_pickle.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_posixshmem.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_posixsubprocess.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_queue.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_random.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_sha1.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_sha2.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_sha3.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_socket.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_ssl.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_statistics.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_struct.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testbuffer.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testcapi.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testclinic.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testimportmultiple.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testinternalcapi.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testmultiphase.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_testsinglephase.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_tkinter.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_uuid.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_xxinterpchannels.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_xxsubinterpreters.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_xxtestfuzz.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/_zoneinfo.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/array.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/audioop.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/binascii.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/cmath.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/fcntl.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/grp.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/mmap.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/nis.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/ossaudiodev.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/pyexpat.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/readline.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/resource.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/select.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/spwd.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/syslog.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/termios.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/unicodedata.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/xxlimited.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/xxlimited_35.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/xxsubtype.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/lib-dynload/zlib.cpython-312-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-10.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-10.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-10.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-10.0.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-14.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-14.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-14.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-14.0.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-6.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-6.0.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-7.1.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-7.1.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-8.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-8.0.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-9.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-9.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-9.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/wininst-9.0.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-arm64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli-arm64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-arm64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui-arm64.exe","unknowns-labeler","no package identified in executable file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"hylang:latest","/usr/local/lib/python3.12/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
