"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/t32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/t64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/pip/_vendor/distlib/w64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:gems-5f5b386","/usr/lib/python3.9/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
