"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:from_engine_v1","/usr/lib/python3.6/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/lib/python3.6/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/lib/python3.6/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/lib/python3.6/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:from_engine_v1","/usr/local/lib/python3.6/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/_cbor2.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/_cffi_backend.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/argon2/_ffi.abi3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/bcrypt/_bcrypt.abi3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/cffi.libs/libffi-806b1a9d.so.6.0.4","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/bindings/_padding.abi3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/ijson/.libs/libyajl-da6a00d5.so.2.1.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/ijson/backends/_yajl2.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/markupsafe/_speedups.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/msgpack/_cmsgpack.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/netifaces.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psutil/_psutil_linux.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psutil/_psutil_posix.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libcom_err-beb60336.so.2.1","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libcrypto-3a9cf061.so.1.1.1d","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libgssapi_krb5-174f8956.so.2.2","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libk5crypto-622ef25b.so.3.1","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libkeyutils-1-ff31573b.2.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libkrb5-fb0d2caa.so.3.3","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libkrb5support-d7ce89d4.so.0.1","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/liblber-2-e85f761a.4.so.2.10.11","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libldap_r-2-b688a282.4.so.2.10.11","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libpq-3d107b13.so.5.11","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libsasl2-6f25e95f.so.3.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libselinux-cf8f9094.so.1","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libsepol-b4f5b513.so.1","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libssl-8b4167bf.so.1.1.1d","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/.libs/libz-a147dcb0.so.1.2.3","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/rapidjson.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/sqlalchemy/cprocessors.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/sqlalchemy/cresultproxy.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/sqlalchemy/cutils.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/twisted/test/raiser.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/wrapt/_wrappers.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/zope/hookable/_zope_hookable.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/zope/interface/_zope_interface_coptimizations.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/usr/local/lib64/python3.6/site-packages/zope/proxy/_zope_proxy_proxy.cpython-36m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:from_engine_v1","/var/lib/dpkg/status","dpkg-db-cataloger","unable to determine packages"
