"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/aiohttp/_frozenlist.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/aiohttp/_helpers.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/aiohttp/_http_parser.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/aiohttp/_http_writer.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/aiohttp/_websocket.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/multidict/_multidict.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/usr/local/lib/python3.7/dist-packages/yarl/_quoting_c.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:vulnerabilities-no-distro-6bde59e","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
